overwrite: true
schema: "./schema.graphql"
generates:
  ./src/generated/graphql.type.ts:
    plugins:
      "typescript":
    config:
      scalars:
        GenericScalar: unknown
        DateTime: unknown
    
