overwrite: true
schema: "./schema.graphql"
documents:
  - "src/main.graphql"
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typed-document-node"
    config:
      defaultScalarType: "unknown"
      preResolveTypes: true
      useTypeImports: true
