// source: samples.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.epi2me.samples.ExperimentMap', null, global);
goog.exportSymbol('proto.epi2me.samples.ExperimentMap.Experiment', null, global);
goog.exportSymbol('proto.epi2me.samples.ExperimentMap.Sample', null, global);
goog.exportSymbol('proto.epi2me.samples.SamplesRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.epi2me.samples.SamplesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.epi2me.samples.SamplesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.epi2me.samples.SamplesRequest.displayName = 'proto.epi2me.samples.SamplesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.epi2me.samples.ExperimentMap = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.epi2me.samples.ExperimentMap, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.epi2me.samples.ExperimentMap.displayName = 'proto.epi2me.samples.ExperimentMap';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.epi2me.samples.ExperimentMap.Experiment = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.epi2me.samples.ExperimentMap.Experiment.repeatedFields_, null);
};
goog.inherits(proto.epi2me.samples.ExperimentMap.Experiment, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.epi2me.samples.ExperimentMap.Experiment.displayName = 'proto.epi2me.samples.ExperimentMap.Experiment';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.epi2me.samples.ExperimentMap.Sample = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.epi2me.samples.ExperimentMap.Sample, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.epi2me.samples.ExperimentMap.Sample.displayName = 'proto.epi2me.samples.ExperimentMap.Sample';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.epi2me.samples.SamplesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.epi2me.samples.SamplesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.epi2me.samples.SamplesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.epi2me.samples.SamplesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    path: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.epi2me.samples.SamplesRequest}
 */
proto.epi2me.samples.SamplesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.epi2me.samples.SamplesRequest;
  return proto.epi2me.samples.SamplesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.epi2me.samples.SamplesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.epi2me.samples.SamplesRequest}
 */
proto.epi2me.samples.SamplesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.epi2me.samples.SamplesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.epi2me.samples.SamplesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.epi2me.samples.SamplesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.epi2me.samples.SamplesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string path = 1;
 * @return {string}
 */
proto.epi2me.samples.SamplesRequest.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.epi2me.samples.SamplesRequest} returns this
 */
proto.epi2me.samples.SamplesRequest.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.epi2me.samples.ExperimentMap.prototype.toObject = function(opt_includeInstance) {
  return proto.epi2me.samples.ExperimentMap.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.epi2me.samples.ExperimentMap} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.epi2me.samples.ExperimentMap.toObject = function(includeInstance, msg) {
  var f, obj = {
    experimentsMap: (f = msg.getExperimentsMap()) ? f.toObject(includeInstance, proto.epi2me.samples.ExperimentMap.Experiment.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.epi2me.samples.ExperimentMap}
 */
proto.epi2me.samples.ExperimentMap.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.epi2me.samples.ExperimentMap;
  return proto.epi2me.samples.ExperimentMap.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.epi2me.samples.ExperimentMap} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.epi2me.samples.ExperimentMap}
 */
proto.epi2me.samples.ExperimentMap.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getExperimentsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.epi2me.samples.ExperimentMap.Experiment.deserializeBinaryFromReader, "", new proto.epi2me.samples.ExperimentMap.Experiment());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.epi2me.samples.ExperimentMap.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.epi2me.samples.ExperimentMap.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.epi2me.samples.ExperimentMap} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.epi2me.samples.ExperimentMap.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getExperimentsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.epi2me.samples.ExperimentMap.Experiment.serializeBinaryToWriter);
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.epi2me.samples.ExperimentMap.Experiment.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.epi2me.samples.ExperimentMap.Experiment.prototype.toObject = function(opt_includeInstance) {
  return proto.epi2me.samples.ExperimentMap.Experiment.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.epi2me.samples.ExperimentMap.Experiment} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.epi2me.samples.ExperimentMap.Experiment.toObject = function(includeInstance, msg) {
  var f, obj = {
    startdate: jspb.Message.getFieldWithDefault(msg, 1, ""),
    samplesList: jspb.Message.toObjectList(msg.getSamplesList(),
    proto.epi2me.samples.ExperimentMap.Sample.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.epi2me.samples.ExperimentMap.Experiment}
 */
proto.epi2me.samples.ExperimentMap.Experiment.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.epi2me.samples.ExperimentMap.Experiment;
  return proto.epi2me.samples.ExperimentMap.Experiment.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.epi2me.samples.ExperimentMap.Experiment} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.epi2me.samples.ExperimentMap.Experiment}
 */
proto.epi2me.samples.ExperimentMap.Experiment.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStartdate(value);
      break;
    case 2:
      var value = new proto.epi2me.samples.ExperimentMap.Sample;
      reader.readMessage(value,proto.epi2me.samples.ExperimentMap.Sample.deserializeBinaryFromReader);
      msg.addSamples(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.epi2me.samples.ExperimentMap.Experiment.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.epi2me.samples.ExperimentMap.Experiment.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.epi2me.samples.ExperimentMap.Experiment} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.epi2me.samples.ExperimentMap.Experiment.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStartdate();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSamplesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.epi2me.samples.ExperimentMap.Sample.serializeBinaryToWriter
    );
  }
};


/**
 * optional string startDate = 1;
 * @return {string}
 */
proto.epi2me.samples.ExperimentMap.Experiment.prototype.getStartdate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.epi2me.samples.ExperimentMap.Experiment} returns this
 */
proto.epi2me.samples.ExperimentMap.Experiment.prototype.setStartdate = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Sample samples = 2;
 * @return {!Array<!proto.epi2me.samples.ExperimentMap.Sample>}
 */
proto.epi2me.samples.ExperimentMap.Experiment.prototype.getSamplesList = function() {
  return /** @type{!Array<!proto.epi2me.samples.ExperimentMap.Sample>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.epi2me.samples.ExperimentMap.Sample, 2));
};


/**
 * @param {!Array<!proto.epi2me.samples.ExperimentMap.Sample>} value
 * @return {!proto.epi2me.samples.ExperimentMap.Experiment} returns this
*/
proto.epi2me.samples.ExperimentMap.Experiment.prototype.setSamplesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.epi2me.samples.ExperimentMap.Sample=} opt_value
 * @param {number=} opt_index
 * @return {!proto.epi2me.samples.ExperimentMap.Sample}
 */
proto.epi2me.samples.ExperimentMap.Experiment.prototype.addSamples = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.epi2me.samples.ExperimentMap.Sample, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.epi2me.samples.ExperimentMap.Experiment} returns this
 */
proto.epi2me.samples.ExperimentMap.Experiment.prototype.clearSamplesList = function() {
  return this.setSamplesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.epi2me.samples.ExperimentMap.Sample.prototype.toObject = function(opt_includeInstance) {
  return proto.epi2me.samples.ExperimentMap.Sample.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.epi2me.samples.ExperimentMap.Sample} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.epi2me.samples.ExperimentMap.Sample.toObject = function(includeInstance, msg) {
  var f, obj = {
    flowcell: jspb.Message.getFieldWithDefault(msg, 1, ""),
    sample: jspb.Message.getFieldWithDefault(msg, 2, ""),
    path: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.epi2me.samples.ExperimentMap.Sample}
 */
proto.epi2me.samples.ExperimentMap.Sample.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.epi2me.samples.ExperimentMap.Sample;
  return proto.epi2me.samples.ExperimentMap.Sample.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.epi2me.samples.ExperimentMap.Sample} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.epi2me.samples.ExperimentMap.Sample}
 */
proto.epi2me.samples.ExperimentMap.Sample.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFlowcell(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSample(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.epi2me.samples.ExperimentMap.Sample.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.epi2me.samples.ExperimentMap.Sample.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.epi2me.samples.ExperimentMap.Sample} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.epi2me.samples.ExperimentMap.Sample.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFlowcell();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSample();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string flowcell = 1;
 * @return {string}
 */
proto.epi2me.samples.ExperimentMap.Sample.prototype.getFlowcell = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.epi2me.samples.ExperimentMap.Sample} returns this
 */
proto.epi2me.samples.ExperimentMap.Sample.prototype.setFlowcell = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string sample = 2;
 * @return {string}
 */
proto.epi2me.samples.ExperimentMap.Sample.prototype.getSample = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.epi2me.samples.ExperimentMap.Sample} returns this
 */
proto.epi2me.samples.ExperimentMap.Sample.prototype.setSample = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string path = 3;
 * @return {string}
 */
proto.epi2me.samples.ExperimentMap.Sample.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.epi2me.samples.ExperimentMap.Sample} returns this
 */
proto.epi2me.samples.ExperimentMap.Sample.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * map<string, Experiment> experiments = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.epi2me.samples.ExperimentMap.Experiment>}
 */
proto.epi2me.samples.ExperimentMap.prototype.getExperimentsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.epi2me.samples.ExperimentMap.Experiment>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      proto.epi2me.samples.ExperimentMap.Experiment));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.epi2me.samples.ExperimentMap} returns this
 */
proto.epi2me.samples.ExperimentMap.prototype.clearExperimentsMap = function() {
  this.getExperimentsMap().clear();
  return this;};


goog.object.extend(exports, proto.epi2me.samples);
